### ISSUE TITLE
Town Autocomplete doesn't save town when typing whole name

### ISSUE THREAD

**Issue by johnneed** [johnneed/GreenUpVermont#235] opened 2018-03-28 11:03 UTC
Steps to reproduce:

1) Go to Team Editor Details screen.
2) Start typing "Burlington" and select "Burlington" before finishing the whole word.
3) Click "save"
4) Go back and notice that town was save.
5) Type out the whole word "Cabot" and click save -- do not select "Cabot"
6) Go back and notice town has not changed.

We probably need to add another event handler to the autocomplete control.

**Comment by kmeyersvt** [comment] 2018-03-29 00:34
I opened a ticket for this too, I also added the info that it is also case sensitive. It doesn't find "colchest" and it doesn't find "COLCHEST".

**Comment by jmargolisvt** [comment] 2018-03-29 22:20
Closing as dupe of https://github.com/johnneed/GreenUpVermont/issues/160

**Closed by jmargolisvt** 2018-03-29 22:20 UTC
Labels: bug
