### ISSUE TITLE
Invitation email is not actionable

### ISSUE THREAD

**Issue by kmeyersvt** [johnneed/GreenUpVermont#174] opened 2018-03-13 14:10 UTC
I received an email inviting me to participate in Green Up Day, but there were no actionable links on the email.  If this is a beginning test, that's fine and you can close this issue, but I wanted to log it.

![image](https://user-images.githubusercontent.com/37085086/37346809-bbab878c-26a6-11e8-999b-b198fcaa3b66.png)

**Comment by johnneed** [comment] 2018-03-14 00:43
duplicate of 50

**Closed by johnneed** 2018-03-14 00:43 UTC
