### ISSUE TITLE
Trying to create a new message when assigned to a team with no name, app crashes.

### ISSUE THREAD

**Issue by kbeaulieu802** [johnneed/GreenUpVermont#94] opened 2018-02-27 15:09 UTC
If a user is assigned to a team that does not have a name set and that user tries to create a new message the app freezes or crashes.

**Comment by johnneed** [comment] 2018-03-08 19:54
Can't reproduce, must have been fixed in a previous bug

**Closed by johnneed** 2018-03-08 19:54 UTC
Labels: MVP, bug
